[tool.poetry]
name = "npz-viewer"
version = "0.1.0"
description = ""
authors = ["Thibaut Vercueil"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
streamlit = "^1.34.0"
matplotlib = "^3.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
